# -*- coding: utf-8 -*-
"""Projelerim adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nwL-4XmcfNczozG2-C3UKu3dLHvntZo
"""

from random import randint   
 
while True:
  rand=randint(1000, 10000)
  rand = str(rand)
  toplam = 0
  for i in rand:
    if rand.count(i) > 1:
      toplam += 1
  else:
    if toplam > 0:
     continue
    else:
      break

sayaç = 0
sonuç = ''

while sayaç < 10:
  sayı = input('Lütfen Tahmininizi Giriniz: ')
  print(f'{10 - (sayaç + 1)} hakkın kaldı!')
   
  if  (not sayı.isdigit()) or len(sayı) != 4:
       print('Lütfen Sayınız Dört Basamaklı Olsun')
       continue
  else:
    count = 0
    for i in sayı:
      if sayı.count(i) > 1:
        count += 1
    else:
      if count > 0:
        print('Her Rakamı Sadece Bir Kere Kullanabilirsin!')
        continue
   

  sonuç = ''
  sayaç += 1
  if sayı == rand:
    print(f'Bravo, {sayaç}. hakkınızda bildiniz')
    break
  else :
    for i in sayı:
      if i not in rand:
        sonuç += ''
      else: 
         if sayı.index(i) == rand.index(i): 
            sonuç += '+'
         else:
            sonuç += '-'
    else:
      print(*sorted(sonuç), 'Haydi Bir Kere Daha Dene!')
else:
  print(f'Ne Yazık Ki Bilemediniz, cevap {rand} olacaktı')